--- 
author: 
  avatar: /assets/images/bio-photo.jpg
  bio: "My awesome biography constrained to a sentence or two goes here."
  links: 
    - 
      icon: "fas fa-fw fa-link"
      label: Website
      url: "https://"
    - 
      icon: "fab fa-fw fa-twitter-square"
      label: Twitter
      url: "https://twitter.com/"
    - 
      icon: "fab fa-fw fa-github"
      label: GitHub
      url: "https://github.com/"
    - 
      icon: "fab fa-fw fa-instagram"
      label: Instagram
      url: "https://instagram.com/"
  name: "First Lastname"
category_archive: 
  path: /categories/
  type: liquid
defaults: 
  - 
    scope: 
      path: ""
      type: posts
    values: 
      author_profile: true
      comments: true
      layout: single
      read_time: true
      related: true
      share: true
  - 
    scope: 
      path: _pages
      type: pages
    values: 
      author_profile: true
      layout: single
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
email: ayishetuseidu13@gmai.com
footer: 
  links: 
    - 
      icon: "fab fa-fw fa-twitter-square"
      label: Twitter
      url: "https://twitter.com/"
    - 
      icon: "fab fa-fw fa-github"
      label: GitHub
      url: "https://github.com/"
    - 
      icon: "fab fa-fw fa-instagram"
      label: Instagram
      url: "https://instagram.com/"
github_username: AyishaSeidu
include: 
  - _pages
markdown: kramdown
minimal_mistakes_skin: default
paginate: 5
paginate_path: "/page:num/"
permalink: "/:categories/:title/"
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
remote_theme: mmistakes/minimal-mistakes
search: true
tag_archive: 
  path: /tags/
  type: liquid
timezone: ~
title: "Ayisha Seidu"
twitter_username: AyishetuSeidu
